# Generated by Django 4.0.4 on 2022-06-11 06:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_user_bio_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[], max_length=100, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='lichess',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='years_playing',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='zoom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
