# Generated by Django 4.0.4 on 2022-06-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_logintoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginToken',
        ),
    ]
