# Generated by Django 4.0.4 on 2022-06-15 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_delete_logintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=10)),
                ('bio', models.CharField(default='', max_length=1000)),
                ('photo', models.ImageField(default='', upload_to='')),
                ('rating', models.SmallIntegerField(default=0)),
                ('years_teaching', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='players',
        ),
        migrations.AddField(
            model_name='meeting',
            name='players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='meetings',
        ),
        migrations.AddField(
            model_name='user',
            name='meetings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.meeting'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('description', models.CharField(default='', max_length=1000)),
                ('entry_fee', models.SmallIntegerField(default=0)),
                ('min_rating', models.SmallIntegerField(default=-1)),
                ('max_rating', models.SmallIntegerField(default=-1)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.professional')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('description', models.CharField(default='', max_length=1000)),
                ('min_rating', models.SmallIntegerField(default=-1)),
                ('max_rating', models.SmallIntegerField(default=-1)),
                ('min_age', models.SmallIntegerField(default=-1)),
                ('max_age', models.SmallIntegerField(default=-1)),
                ('avg_class_size', models.SmallIntegerField(default=-1)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.professional')),
            ],
        ),
    ]
