# Generated by Django 4.0.4 on 2022-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_professional_remove_meeting_players_meeting_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_playing',
            field=models.SmallIntegerField(default=0),
        ),
    ]
