# Generated by Django 4.0.4 on 2022-06-18 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_user_dob_alter_user_years_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
