# Generated by Django 4.0.4 on 2022-06-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_requestmeeting_recipient_requestmeeting_sender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestMeeting',
        ),
    ]
