# Generated by Django 4.0.4 on 2022-06-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_requestmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='time',
        ),
    ]
