# Generated by Django 4.0.4 on 2022-06-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_meetingrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
