# Generated by Django 4.0.4 on 2022-06-20 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_meetingrequest_recipient_meetingrequest_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequest',
            name='recipient',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, related_name='going_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='sender',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, related_name='coming_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
