# Generated by Django 4.0.4 on 2022-06-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_requestmeeting_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='recipient',
            field=models.CharField(max_length=200, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='sender',
            field=models.CharField(max_length=200, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='time',
            field=models.DateTimeField(null='true'),
            preserve_default='true',
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default='')),
                ('message', models.CharField(default='', max_length=1000)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='going_to', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='reqs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.meetingrequest'),
        ),
    ]
