# Generated by Django 4.0.4 on 2022-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_delete_requestmeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, null='true')),
                ('recipient', models.CharField(max_length=200, null='true')),
                ('time', models.DateTimeField(null='true')),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
