# Generated by Django 4.0.4 on 2022-06-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_delete_requestmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrequest',
            name='id',
        ),
    ]
