# Generated by Django 4.0.4 on 2022-06-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_meetingrequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrequest',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='time',
        ),
    ]
