# Generated by Django 4.0.4 on 2022-06-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_meetingrequest_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='recipient',
            field=models.CharField(max_length=100, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='sender',
            field=models.CharField(max_length=100, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='time',
            field=models.DateTimeField(default=''),
        ),
    ]
