# Generated by Django 4.0.4 on 2022-06-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_meetingrequest_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrequest',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='time',
        ),
    ]
