# Generated by Django 4.0.4 on 2022-07-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_meeting_players_meeting_player1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='meetings',
        ),
    ]
