# Generated by Django 4.0.4 on 2022-07-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_user_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(default=''),
        ),
    ]
